### ISSUE TITLE
NPE when using latest version (commit 2e65bdfbae9db60e9dac30d45fb0b7947d523a76) on "tutorial" command

### ISSUE THREAD

**Issue by Hoolean** [hawkfalcon/ServerTutorial#11]
[Reported by a user in IRC.](https://gist.githubusercontent.com/Hoolean/502003f941557c9fc85c/raw/70907f4b991bfd1f2447b0e3dbd6ee957f8b8a43/gistfile1.txt)

If fixed, user's IRC nick was *Cheeze*. :palm_tree:

**Comment by hawkfalcon** [comment]
I no longer provide support for this. Anyone is welcome to take this over.

**Comment by hawkfalcon** [comment]
Fixed
