### ISSUE TITLE
Internal Server Error with KCauldron 1.7.10

### ISSUE THREAD

**Issue by xJonL** [hawkfalcon/ServerTutorial#18]
KCauldron is a revived version of cauldron. Cauldron allows you to run mods alongside with bukkit.

Tested with ServerTutorial v1.3.1, v1.2.1, and v1.2

https://gist.github.com/xJonL/cf64634b24e31cb4a071
https://gist.github.com/xJonL/9424ffb60c0651732e9f

**Comment by frostalf** [comment]
I can't not say that Server Tutorial will ever be compatible with KCauldron, given the fact, that while although it may contain bukkit, there are still some major differences especially in how bukkit is combined with forge. Both Forge and Bukkit handle packets differently as well as Bukkit's way of handling commands is not using minecraft vanilla command system. I am in the process of pushing a new version of Server Tutorial. However, I can not say that it will be compatible either. Thanks for letting us know that it currently isn't.

**Comment by xJonL** [comment]
Awesome, I'll try how your new build!
