### ISSUE TITLE
One time tutorial

### ISSUE THREAD

**Issue by mrequinox3** [hawkfalcon/ServerTutorial#19]
Is it possible to make the plugin run the tutorial only one time for that player? I have added rewards and if players play the tutorial more than one time they will get more money than necessary.

**Comment by hawkfalcon** [comment]
I somehow missed this. The plugin should only ever give money once, regardless of how many times they do the tutorial.

**Comment by mrequinox3** [comment]
Ohh, I have somehow forgotten about this thread.
Yea, exactly.

**Comment by hawkfalcon** [comment]
Is this not the case? I check if they player has done that tutorial before giving the money already:
https://github.com/hawkfalcon/ServerTutorial/blob/a3f774fc0d74a48b9f96c620c20a6e3a8bcd7eba/src/main/java/pw/hwk/tutorial/TutorialListener.java#L232

**Comment by mrequinox3** [comment]
Well, you have responded to the thread and I said yes, you are right - you missed that feature.
If you have something that is preventing the case we are talking about in the code, well your code is not working then and you might have to change it.
Check if the if-statement is in the right position, in the right event, and its' expression is correct - including the methods you are using inside it.

**Comment by hawkfalcon** [comment]
Found the bug. Didn't even realize it existed. Thank you! Will patch with next version.

**Comment by mrequinox3** [comment]
Congratz! Let's nail that sh*t! :D
Thank you too! ^_^
