### ISSUE TITLE
Color codes not supported

### ISSUE THREAD

**Issue by DevinNL** [hawkfalcon/ServerTutorial#21]
I tried to use a essentials color code (& codes) but it just gave me an error in the console, the tutorials are really boring without color, so can this please be fixed?

**Comment by DevinNL** [comment]
Okay, I found out that color codes are supported, but not on the first word of a sentence.... That will cause the tutorial te be unlisted/unloaded

**Comment by DevinNL** [comment]
I fixed it! I used these symbols ' ' at the end and beginning of the sentence in the config (data.yml), That fixed my issue.

**Comment by hawkfalcon** [comment]
Odd. I'll look into it.

**Comment by frostalf** [comment]
Could you post this error that happened? Also could you provide examples of what you are inputting as well? Will make this easier to fix or investigate.

**Comment by frostalf** [comment]
Could not replicate and no other information has been posted about this, therefore closing.
