### ISSUE TITLE
Players break on tutorial end when in an opposite gamemode as the tutorial and flying prior to joining.

### ISSUE THREAD

**Issue by mibby** [hawkfalcon/ServerTutorial#34]
@hawkfalcon @frostalf 
	
ServerTutorial v2.2.3
Spigot 1.11.2

If a player is in creative/spectate mode and flying in the air when they join a tutorial, they are not able to exit the tutorial when it ends. It tries to return you but fails, then sends you back to the last stage of the tutorial and spams you with the end message. It keeps trying to tp you somewhere and fails so you just flash in and out of existence at the last point in the tutorial until you log out. Then upon relogging in, you're still half in the tutorial so you can't move. Only way to fix that is to go through the tutorial again

If you are in creative and on the ground when joining, you are fine. If you are in survival and flying when joining, you are fine. It seems to break when you are in an opposite gamemode that the tutorial is set to and flying prior to joining.

My tutorial when testing is set to Survival.
```
    gamemode: SURVIVAL
```

**Comment by frostalf** [comment]
I am almost finished with the update. The update will remove the changing of the gamemode setting as it is pointless and so far don't see a purpose behind this. Thanks for the report.

**Comment by mibby** [comment]
Sounds good. As long as the tutorial obeys the gamemode the player enters from. :)
